root: true

extends:
  - "@samuelmeuli/eslint-config/react-typescript"
  - "prettier"
  - "prettier/@typescript-eslint"

env:
  browser: true
  node: true

rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - "rollup.config.js"
        - ".storybook/**/*.js"
        - "stories/**/*.jsx"
  react/jsx-sort-default-props: off
